modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="christopherscreatures" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Christopher's Creatures" #mandatory
logoFile="christopherscreature.png" #optional
credits="To be added" #optional
authors="Akaneo, Doctor Hyena" #optional
description='''To be added'''
[[dependencies.christopherscreatures]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.christopherscreatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
